"""add_telemetry_raw

Revision ID: 5421ecc75138
Revises: 7ce464b91137
Create Date: 2026-05-21 18:14:01.336550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5421ecc75138'
down_revision: Union[str, None] = '7ce464b91137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_raw',
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ambient_t', sa.Float(), nullable=True),
    sa.Column('ambient_h', sa.Float(), nullable=True),
    sa.Column('diss_t', sa.Float(), nullable=True),
    sa.Column('diss_h', sa.Float(), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('pid_out', sa.Float(), nullable=True),
    sa.Column('uptime_ms', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_raw')
    # ### end Alembic commands ###
